version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/aws-code-deploy-demo

hooks:
  ApplicationStart:
    - location: aws-scripts/app-start.sh
      timeout: 200

  BeforeInstall:
    - location: aws-scripts/before-install.sh
      timeout: 300

  AfterInstall:
    - location: aws-scripts/after-install.sh
      timeout: 300

  ApplicationStart:
    - location: aws-scripts/app-start.sh
      timeout: 300

  ApplicationStop:
    - location: aws-scripts/app-stop.sh
      timeout: 300
